export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const FETCH_ACCOUNTS_FAILED = "FETCH_ACCOUNTS_FAILED";

export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const FETCH_TRANSACTIONS_FAILED = "FETCH_TRANSACTIONS_FAILED";

export const SET_TRANSACTION_DETAIL = "SET_TRANSACTION_DETAIL";
export const FETCH_TRANSACTION_DETAIL_FAILED = "FETCH_TRANSACTION_DETAIL_FAILED";